/* eslint-disable import/prefer-default-export */
import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // deletes all existing entries
  await knex('orders_books').del();
  await knex('orders').del();
  await knex('users').del();
  await knex('social_profiles').del();
  await knex('books_authors').del();
  await knex('books').del();
  await knex('authors').del();
  await knex('categories').del();

  // users
  await knex('users').insert([
    {
      id: 1,
      firstName: 'phuc',
      lastName: 'nguyen',
      username: 'phuc1nguyen',
      email: 'phuc.ng13988@gmail.com',
      password: '123456',
      phone: '0918200000',
      avatar: 'https://cdn.discordapp.com/embed/avatars/4.png',
      gender: 'male',
      role: 'admin',
      active: true,
    },
    {
      id: 2,
      firstName: 'Muffin',
      lastName: 'Gould',
      username: 'mgould1',
      email: 'mgould1@bloglovin.com',
      password: 'tYEpInch',
      phone: '113-219-4425',
      avatar: 'https://robohash.org/autcumut.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: true,
    },
    {
      id: 3,
      firstName: 'Evaleen',
      lastName: 'Ratnage',
      username: 'eratnage2',
      email: 'eratnage2@soundcloud.com',
      password: 'nJVa0RCB',
      phone: '146-145-3810',
      avatar:
        'https://robohash.org/placeatetpraesentium.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 4,
      firstName: 'Kathryn',
      lastName: 'Hendrick',
      username: 'khendrick3',
      email: 'khendrick3@wp.com',
      password: '72RfIK',
      phone: '899-972-6304',
      avatar:
        'https://robohash.org/providentutquisquam.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: false,
    },
    {
      id: 5,
      firstName: 'Deonne',
      lastName: 'Frawley',
      username: 'dfrawley4',
      email: 'dfrawley4@moonfruit.com',
      password: 'in9HltvIxSFe',
      phone: '890-218-3921',
      avatar:
        'https://robohash.org/eaquerepudiandaeaut.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 6,
      firstName: 'Nappy',
      lastName: 'MacNeely',
      username: 'nmacneely5',
      email: 'nmacneely5@engadget.com',
      password: '4rBLynHI',
      phone: '466-462-4604',
      avatar:
        'https://robohash.org/inventorealiquamfugit.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: true,
    },
    {
      id: 7,
      firstName: 'Kerr',
      lastName: 'Collings',
      username: 'kcollings6',
      email: 'kcollings6@youku.com',
      password: 'eIpWwiWQ6RvO',
      phone: '232-142-7482',
      avatar: 'https://robohash.org/iureenimrecusandae.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: false,
    },
    {
      id: 8,
      firstName: 'Charis',
      lastName: 'Paiton',
      username: 'cpaiton7',
      email: 'cpaiton7@shinystat.com',
      password: 'pgr4x1XnF',
      phone: '101-260-8967',
      avatar:
        'https://robohash.org/consecteturiureamet.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 9,
      firstName: 'Kissiah',
      lastName: 'de Clerc',
      username: 'kdeclerc8',
      email: 'kdeclerc8@geocities.com',
      password: 'R562Cq5WHz5o',
      phone: '969-660-1835',
      avatar: 'https://robohash.org/eligendiatotam.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: false,
    },
    {
      id: 10,
      firstName: 'Saunderson',
      lastName: 'Klasen',
      username: 'sklasen9',
      email: 'sklasen9@blogger.com',
      password: 'bqCR0x76c',
      phone: '676-194-0450',
      avatar: 'https://robohash.org/dolorestimpedit.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: true,
    },
    {
      id: 11,
      firstName: 'Pam',
      lastName: 'Bullion',
      username: 'pbulliona',
      email: 'pbulliona@unc.edu',
      password: 'dkHIkm6Rk',
      phone: '724-444-2850',
      avatar: 'https://robohash.org/inutsunt.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: false,
    },
    {
      id: 12,
      firstName: 'Lorinda',
      lastName: 'Lambregts',
      username: 'llambregtsb',
      email: 'llambregtsb@cocolog-nifty.com',
      password: 'RKR3R7XhbnY2',
      phone: '954-245-8795',
      avatar: 'https://robohash.org/maximeeosdolorum.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 13,
      firstName: 'Bayard',
      lastName: 'Leyson',
      username: 'bleysonc',
      email: 'bleysonc@shinystat.com',
      password: 'IUn8ow',
      phone: '335-294-9190',
      avatar: 'https://robohash.org/estomnissapiente.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: false,
    },
    {
      id: 14,
      firstName: 'Preston',
      lastName: 'Goudy',
      username: 'pgoudyd',
      email: 'pgoudyd@dailymotion.com',
      password: 'fv6aeV',
      phone: '837-731-7401',
      avatar:
        'https://robohash.org/placeataspernaturquis.png?size=50x50&set=set1',
      gender: 'other',
      role: 'customer',
      active: true,
    },
    {
      id: 15,
      firstName: 'Morgana',
      lastName: 'Masson',
      username: 'mmassone',
      email: 'mmassone@rakuten.co.jp',
      password: 'qCQcqKkehyQx',
      phone: '651-238-7437',
      avatar:
        'https://robohash.org/etvoluptatemexcepturi.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 16,
      firstName: 'Marcus',
      lastName: 'Brearton',
      username: 'mbreartonf',
      email: 'mbreartonf@fc2.com',
      password: 'WmEtLINL',
      phone: '593-971-3147',
      avatar: 'https://robohash.org/eiusoptionemo.png?size=50x50&set=set1',
      gender: 'other',
      role: 'customer',
      active: true,
    },
    {
      id: 17,
      firstName: 'Bette',
      lastName: 'Wigginton',
      username: 'bwiggintong',
      email: 'bwiggintong@craigslist.org',
      password: '3aie15Cbj',
      phone: '514-345-9255',
      avatar:
        'https://robohash.org/dolorumrepellatillum.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 18,
      firstName: 'Hewie',
      lastName: 'Ivanisov',
      username: 'hivanisovh',
      email: 'hivanisovh@xing.com',
      password: 'JZzWbJ2vC',
      phone: '464-154-2148',
      avatar:
        'https://robohash.org/velvoluptatedolores.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: true,
    },
    {
      id: 19,
      firstName: 'Fern',
      lastName: "O'Neal",
      username: 'foneali',
      email: 'foneali@networksolutions.com',
      password: 'PX47hNZnt',
      phone: '632-128-1368',
      avatar: 'https://robohash.org/estvoluptasest.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: false,
    },
    {
      id: 20,
      firstName: 'Elsie',
      lastName: 'Roadknight',
      username: 'eroadknightj',
      email: 'eroadknightj@house.gov',
      password: 'UmZ37BAcTFZ9',
      phone: '152-896-3478',
      avatar:
        'https://robohash.org/eosblanditiismolestias.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 21,
      firstName: 'Holden',
      lastName: 'Verner',
      username: 'hvernerk',
      email: 'hvernerk@sourceforge.net',
      password: '7lUZxbl0',
      phone: '206-415-3825',
      avatar: 'https://robohash.org/uteumvoluptatum.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: false,
    },
    {
      id: 22,
      firstName: 'Gladys',
      lastName: 'Privost',
      username: 'gprivostl',
      email: 'gprivostl@bravesites.com',
      password: '4vbpBC',
      phone: '213-632-7822',
      avatar:
        'https://robohash.org/voluptatemdolorumporro.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: false,
    },
    {
      id: 23,
      firstName: 'Kassia',
      lastName: 'Aspinal',
      username: 'kaspinalm',
      email: 'kaspinalm@baidu.com',
      password: 'HwcPIz7JSFx',
      phone: '120-638-8132',
      avatar: 'https://robohash.org/laboreetiusto.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 24,
      firstName: 'Gardener',
      lastName: 'Merrydew',
      username: 'gmerrydewn',
      email: 'gmerrydewn@bandcamp.com',
      password: 'AvfR8gC8uGvZ',
      phone: '148-505-5092',
      avatar: 'https://robohash.org/autadaut.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: true,
    },
    {
      id: 25,
      firstName: 'Tadeo',
      lastName: 'Aukland',
      username: 'tauklando',
      email: 'tauklando@skype.com',
      password: '6pg9IFRKm',
      phone: '345-490-1239',
      avatar:
        'https://robohash.org/fugiatnobisconsectetur.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: true,
    },
    {
      id: 26,
      firstName: 'Carmon',
      lastName: 'Kemsley',
      username: 'ckemsleyp',
      email: 'ckemsleyp@dion.ne.jp',
      password: 'Ucb4Y4t',
      phone: '449-999-4214',
      avatar: 'https://robohash.org/odioquiafugiat.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 27,
      firstName: 'Chastity',
      lastName: 'Diglin',
      username: 'cdiglinq',
      email: 'cdiglinq@amazon.com',
      password: '0Vza93E',
      phone: '954-832-9779',
      avatar: 'https://robohash.org/culpamaximefacilis.png?size=50x50&set=set1',
      gender: 'other',
      role: 'customer',
      active: false,
    },
    {
      id: 28,
      firstName: 'Lena',
      lastName: 'Hambright',
      username: 'lhambrightr',
      email: 'lhambrightr@ocn.ne.jp',
      password: 'O60tnezG',
      phone: '272-172-6944',
      avatar: 'https://robohash.org/isteundequam.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 29,
      firstName: 'Hadrian',
      lastName: 'Zotto',
      username: 'hzottos',
      email: 'hzottos@sogou.com',
      password: '3Um9E5',
      phone: '915-456-2300',
      avatar: 'https://robohash.org/dignissimossitqui.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: true,
    },
    {
      id: 30,
      firstName: 'Vivian',
      lastName: 'Gockelen',
      username: 'vgockelent',
      email: 'vgockelent@census.gov',
      password: 'Axcp7K',
      phone: '141-587-7426',
      avatar:
        'https://robohash.org/facilisvoluptateexpedita.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: false,
    },
    {
      id: 31,
      firstName: 'Linnea',
      lastName: 'Gorstidge',
      username: 'lgorstidgeu',
      email: 'lgorstidgeu@unblog.fr',
      password: 'q4FGlp70',
      phone: '689-867-8299',
      avatar:
        'https://robohash.org/voluptasconsequaturporro.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 32,
      firstName: 'Vanya',
      lastName: 'MacElroy',
      username: 'vmacelroyv',
      email: 'vmacelroyv@berkeley.edu',
      password: 'EZNJljcT',
      phone: '159-155-6267',
      avatar: 'https://robohash.org/undeutmaxime.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: true,
    },
    {
      id: 33,
      firstName: 'Benedetta',
      lastName: 'Glidden',
      username: 'bgliddenw',
      email: 'bgliddenw@latimes.com',
      password: 'aAVL8XLSOl',
      phone: '553-482-6588',
      avatar: 'https://robohash.org/utdoloreligendi.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 34,
      firstName: 'Rici',
      lastName: 'Esseby',
      username: 'ressebyx',
      email: 'ressebyx@4shared.com',
      password: '5M0ybZ1n',
      phone: '708-329-8236',
      avatar:
        'https://robohash.org/voluptatesiustocorrupti.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: false,
    },
    {
      id: 35,
      firstName: 'Guthrey',
      lastName: 'Cusworth',
      username: 'gcusworthy',
      email: 'gcusworthy@geocities.jp',
      password: '3o9JxsdG2Rwa',
      phone: '139-955-8489',
      avatar: 'https://robohash.org/etconsecteturiure.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: false,
    },
    {
      id: 36,
      firstName: 'Aurthur',
      lastName: 'Sothcott',
      username: 'asothcottz',
      email: 'asothcottz@altervista.org',
      password: 'c5RXIdB',
      phone: '472-321-1446',
      avatar: 'https://robohash.org/etminusipsam.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: false,
    },
    {
      id: 37,
      firstName: 'Joellyn',
      lastName: 'Pakeman',
      username: 'jpakeman10',
      email: 'jpakeman10@businessweek.com',
      password: 'LjIyfr8PnpIy',
      phone: '232-406-7278',
      avatar: 'https://robohash.org/harumquiinventore.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: false,
    },
    {
      id: 38,
      firstName: 'Barrie',
      lastName: 'Quarless',
      username: 'bquarless11',
      email: 'bquarless11@stanford.edu',
      password: 'PR2VtbCBeq2C',
      phone: '467-626-4741',
      avatar:
        'https://robohash.org/voluptatempariaturquibusdam.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: true,
    },
    {
      id: 39,
      firstName: 'Melania',
      lastName: 'Teesdale',
      username: 'mteesdale12',
      email: 'mteesdale12@va.gov',
      password: 'HQgIX7y',
      phone: '500-849-0687',
      avatar: 'https://robohash.org/autquiimpedit.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: false,
    },
    {
      id: 40,
      firstName: 'Purcell',
      lastName: 'Brazelton',
      username: 'pbrazelton13',
      email: 'pbrazelton13@nsw.gov.au',
      password: 'lwcabYjmL2',
      phone: '279-141-6328',
      avatar: 'https://robohash.org/solutaquinostrum.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: true,
    },
    {
      id: 41,
      firstName: 'Donavon',
      lastName: 'Olerenshaw',
      username: 'dolerenshaw14',
      email: 'dolerenshaw14@craigslist.org',
      password: '1qDNE9i8634J',
      phone: '776-541-6683',
      avatar: 'https://robohash.org/idveroaspernatur.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: false,
    },
    {
      id: 42,
      firstName: 'Orran',
      lastName: 'McGifford',
      username: 'omcgifford15',
      email: 'omcgifford15@privacy.gov.au',
      password: 'AQ56tP',
      phone: '142-134-6741',
      avatar: 'https://robohash.org/porrolaboreet.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: false,
    },
    {
      id: 43,
      firstName: 'Celle',
      lastName: 'Gelder',
      username: 'cgelder16',
      email: 'cgelder16@fc2.com',
      password: '3jC3qEO46Q',
      phone: '383-905-4197',
      avatar: 'https://robohash.org/nihilinventorevel.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 44,
      firstName: 'Sanders',
      lastName: 'Hazlewood',
      username: 'shazlewood17',
      email: 'shazlewood17@nifty.com',
      password: 'ctdoiSu',
      phone: '849-405-9207',
      avatar: 'https://robohash.org/etutet.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: false,
    },
    {
      id: 45,
      firstName: 'Olenka',
      lastName: 'Symers',
      username: 'osymers18',
      email: 'osymers18@msn.com',
      password: '2gUQMxUj8',
      phone: '806-281-8013',
      avatar: 'https://robohash.org/etadest.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 46,
      firstName: 'Thaine',
      lastName: 'Durnin',
      username: 'tdurnin19',
      email: 'tdurnin19@cargocollective.com',
      password: '3rJpiIzq',
      phone: '667-547-7684',
      avatar:
        'https://robohash.org/ullamconsequaturneque.png?size=50x50&set=set1',
      gender: 'male',
      role: 'customer',
      active: false,
    },
    {
      id: 47,
      firstName: 'Jerrilyn',
      lastName: 'Crittal',
      username: 'jcrittal1a',
      email: 'jcrittal1a@jugem.jp',
      password: 'gaaS0R76Rz',
      phone: '514-521-2103',
      avatar:
        'https://robohash.org/temporibusestrepellat.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: false,
    },
    {
      id: 48,
      firstName: 'Cissy',
      lastName: 'Kristiansen',
      username: 'ckristiansen1b',
      email: 'ckristiansen1b@reddit.com',
      password: 'sEQQtNQE',
      phone: '205-447-3053',
      avatar:
        'https://robohash.org/blanditiisveniamsoluta.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: false,
    },
    {
      id: 49,
      firstName: 'Gretchen',
      lastName: 'Davies',
      username: 'gdavies1c',
      email: 'gdavies1c@usnews.com',
      password: 'NUVA2UsltwrQ',
      phone: '972-701-2082',
      avatar: 'https://robohash.org/eosdelectusaut.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: true,
    },
    {
      id: 50,
      firstName: 'Daisie',
      lastName: 'Averill',
      username: 'daverill1d',
      email: 'daverill1d@blogspot.com',
      password: 'itIA3fA3',
      phone: '220-609-4723',
      avatar: 'https://robohash.org/utanimiex.png?size=50x50&set=set1',
      gender: 'female',
      role: 'customer',
      active: false,
    },
  ]);

  // social profiles
  await knex('social_profiles').insert([
    {
      id: 1,
      userId: 1,
      provider: 'google',
      username: 'PN',
      avatar: 'https://cdn.discordapp.com/embed/avatars/4.png',
    },
  ]);

  // orders
  await knex('orders').insert([
    {
      id: 1,
      userId: 1,
      paymentMethod: 'cash',
      paymentStatus: 'paid',
      shippingType: 'pick up',
      shippingAddress: JSON.stringify({
        number: 25,
        street: 'Doan Thi Diem',
        district: 'Dong Da',
        city: 'Hanoi',
      }),
      quantity: 1,
      total: 230000,
      shippingCost: 20000,
      grandTotal: 250000,
      isCart: false,
    },
  ]);

  // authors
  await knex('authors').insert([
    {
      id: 1,
      name: 'Livia Palleske',
      description:
        'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.',
      slug: 'Reduced',
    },
    {
      id: 2,
      name: 'Sabrina Cossom',
      description:
        'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
      slug: 'concept',
    },
    {
      id: 3,
      name: 'Jane Caudle',
      description:
        'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.',
      slug: 'Open-source',
    },
    {
      id: 4,
      name: 'Cullen Surridge',
      description:
        'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',
      slug: 'hybrid',
    },
    {
      id: 5,
      name: 'Lora Moriarty',
      description:
        'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.',
      slug: 'human-resource',
    },
    {
      id: 6,
      name: 'Prescott Hanby',
      description:
        'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
      slug: 'monitoring',
    },
    {
      id: 7,
      name: 'Laverne Berick',
      description:
        'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
      slug: 'radical',
    },
    {
      id: 8,
      name: 'Rupert Wakeling',
      description:
        'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.',
      slug: 'maximized',
    },
    {
      id: 9,
      name: 'Laura McIntee',
      description:
        'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.',
      slug: 'upward-trending',
    },
    {
      id: 10,
      name: "Nicolette O'Sherrin",
      description:
        'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.',
      slug: 'upward-trending',
    },
    {
      id: 11,
      name: 'Cherin Fysh',
      description:
        'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
      slug: 'structure',
    },
    {
      id: 12,
      name: 'Gretel Sharrier',
      description:
        'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.',
      slug: 'Re-engineered',
    },
    {
      id: 13,
      name: 'Odey Seabert',
      description:
        'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.',
      slug: 'hierarchy',
    },
    {
      id: 14,
      name: 'Anastassia Jakel',
      description:
        'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',
      slug: 'software',
    },
    {
      id: 15,
      name: 'Pattin Finlayson',
      description:
        'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.',
      slug: 'clear-thinking',
    },
    {
      id: 16,
      name: 'Viole McInteer',
      description:
        'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
      slug: 'asynchronous',
    },
    {
      id: 17,
      name: 'Bancroft McLinden',
      description:
        'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
      slug: 'solution-oriented',
    },
    {
      id: 18,
      name: 'Silvana Chatten',
      description:
        'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.',
      slug: 'multimedia',
    },
    {
      id: 19,
      name: 'Ellene Dunlea',
      description:
        'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.',
      slug: 'Future-proofed',
    },
    {
      id: 20,
      name: 'Sydney Crome',
      description:
        'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.',
      slug: 'directional',
    },
    {
      id: 21,
      name: 'Carl Keepin',
      description:
        'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
      slug: 'Grass-roots',
    },
    {
      id: 22,
      name: 'Christen Levicount',
      description:
        'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.',
      slug: 'intranet',
    },
    {
      id: 23,
      name: 'Harley Smitherman',
      description:
        'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.',
      slug: 'neutral',
    },
    {
      id: 24,
      name: 'Raddie Liff',
      description:
        'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
      slug: 'content-based',
    },
    {
      id: 25,
      name: 'Hillyer Rene',
      description:
        'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',
      slug: 'help-desk',
    },
    {
      id: 26,
      name: 'Opalina MacNish',
      description:
        'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.',
      slug: 'policy',
    },
    {
      id: 27,
      name: 'Roderich Arnaut',
      description:
        'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.',
      slug: 'productivity',
    },
    {
      id: 28,
      name: 'Karry Haster',
      description:
        'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.',
      slug: 'architecture',
    },
    {
      id: 29,
      name: 'Katherine Petticrew',
      description:
        'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.',
      slug: 'Programmable',
    },
    {
      id: 30,
      name: 'Wenonah Bosley',
      description:
        'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.',
      slug: 'Profound',
    },
    {
      id: 31,
      name: 'Edwina Tamas',
      description:
        'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',
      slug: 'composite',
    },
    {
      id: 32,
      name: 'Reinhard Haste',
      description:
        'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
      slug: 'Self-enabling',
    },
    {
      id: 33,
      name: 'Rozalie Flippelli',
      description: 'Etiam faucibus cursus urna. Ut tellus.',
      slug: 'focus group',
    },
    {
      id: 34,
      name: 'Theodore Klimsch',
      description:
        'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.',
      slug: 'executive',
    },
    {
      id: 35,
      name: 'Arni Greener',
      description:
        'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.',
      slug: 'needs-based',
    },
    {
      id: 36,
      name: 'Ulysses Sadd',
      description:
        'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.',
      slug: 'Quality-focused',
    },
    {
      id: 37,
      name: 'Emmanuel Challens',
      description:
        'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',
      slug: 'real-time',
    },
    {
      id: 38,
      name: 'Bronny Buswell',
      description:
        'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.',
      slug: 'interface',
    },
    {
      id: 39,
      name: 'Casie Yitzhok',
      description:
        'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.',
      slug: 'next generation',
    },
    {
      id: 40,
      name: 'Christalle Featherston',
      description:
        'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.',
      slug: 'Upgradable',
    },
    {
      id: 41,
      name: 'Harwilll Kem',
      description:
        'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.',
      slug: 'Exclusive',
    },
    {
      id: 42,
      name: 'Feliza Jurgensen',
      description:
        'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
      slug: 'focus group',
    },
    {
      id: 43,
      name: 'Gaile Conigsby',
      description:
        'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.',
      slug: 'methodical',
    },
    {
      id: 44,
      name: 'Sorcha Ivanaev',
      description:
        'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',
      slug: 'Open-source',
    },
    {
      id: 45,
      name: 'Charo Gillies',
      description:
        'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.',
      slug: 'secondary',
    },
    {
      id: 46,
      name: 'Charo Loisi',
      description:
        'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',
      slug: 'application',
    },
    {
      id: 47,
      name: 'Lorna Ramble',
      description:
        'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.',
      slug: 'Proactive',
    },
    {
      id: 48,
      name: 'Maxy Poundesford',
      description:
        'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.',
      slug: 'directional',
    },
    {
      id: 49,
      name: 'Hillard Fatharly',
      description:
        'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
      slug: 'Phased',
    },
    {
      id: 50,
      name: 'Querida Carabine',
      description:
        'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.',
      slug: 'attitude',
    },
  ]);

  // categories
  await knex('categories').insert([
    {
      id: 1,
      parentId: 2,
      name: 'Retaining Wall and Brick Pavers',
      slug: 'installation',
      active: false,
    },
    {
      id: 2,
      parentId: 6,
      name: 'Exterior Signage',
      slug: 'Public-key',
      active: false,
    },
    {
      id: 3,
      parentId: 6,
      name: 'Termite Control',
      slug: 'Vision-oriented',
      active: false,
    },
    {
      id: 4,
      parentId: 5,
      name: 'Waterproofing & Caulking',
      slug: 'scalable',
      active: false,
    },
    {
      id: 5,
      parentId: 0,
      name: 'Science Fiction',
      slug: 'leverage',
      active: false,
    },
    {
      id: 6,
      parentId: 0,
      name: 'Rebar & Wire Mesh Install',
      slug: 'Public-key',
      active: true,
    },
    {
      id: 7,
      parentId: 6,
      name: 'Soft Flooring and Base',
      slug: 'portal',
      active: false,
    },
    {
      id: 8,
      parentId: 6,
      name: 'Plumbing & Medical Gas',
      slug: 'bifurcated',
      active: true,
    },
    {
      id: 9,
      parentId: 3,
      name: 'Roofing (Asphalt)',
      slug: 'utilisation',
      active: false,
    },
    {
      id: 10,
      parentId: 5,
      name: 'Glass & Glazing',
      slug: 'needs-based',
      active: true,
    },
  ]);

  // books
  await knex('books').insert([
    {
      id: 1,
      categoryId: 8,
      authorId: 12,
      title: 'It Runs in the Family',
      description:
        'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.',
      publisher: 'Galantamine',
      publishedDate: 'Aenean fermentum.',
      pages: 833,
      dimensions: 'Diverse',
      language: 'Chinese',
      isbn: '445734982-8',
      condition: 'new',
      price: 907856,
      currentStock: 61,
      soldCopies: 13,
      thumbnail:
        'https://robohash.org/omnisaliquamearum.png?size=50x75&set=set1',
      photos: null,
      slug: 'User-centric',
      active: true,
    },
    {
      id: 2,
      categoryId: 1,
      authorId: 39,
      title: 'Whistle Down the Wind',
      description:
        'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.',
      publisher: 'Risperidone',
      publishedDate: 'Donec semper sapien a libero.',
      pages: 282,
      dimensions: 'methodical',
      language: 'Danish',
      isbn: '432156153-1',
      condition: 'new',
      price: 382588,
      currentStock: 98,
      soldCopies: 27,
      thumbnail: 'https://robohash.org/idrepellatad.png?size=50x75&set=set1',
      photos: 'augue quam sollicitudin vitae',
      slug: 'policy',
      active: false,
    },
    {
      id: 3,
      categoryId: 4,
      authorId: 10,
      title: 'First Sunday',
      description:
        'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
      publisher: 'Glipizide',
      publishedDate: 'Pellentesque at nulla.',
      pages: 166,
      dimensions: 'background',
      language: 'Swahili',
      isbn: '772793657-X',
      condition: 'used',
      price: 1367428,
      currentStock: 46,
      soldCopies: 15,
      thumbnail: 'https://robohash.org/sedipsamharum.png?size=50x75&set=set1',
      photos: 'adipiscing molestie hendrerit at vulputate',
      slug: 'knowledge base',
      active: false,
    },
    {
      id: 4,
      categoryId: 1,
      authorId: 34,
      title: 'Roadie',
      description:
        'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.',
      publisher: 'BuPROPion Hydrochloride',
      publishedDate: 'Vestibulum ante ipsum primis in odio.',
      pages: 962,
      dimensions: 'neural-net',
      language: 'Tajik',
      isbn: '824786980-2',
      condition: 'used',
      price: 1481918,
      currentStock: 70,
      soldCopies: 8,
      thumbnail: 'https://robohash.org/laborumnonalias.png?size=50x75&set=set1',
      photos: 'eget nunc donec quis orci',
      slug: 'forecast',
      active: false,
    },
    {
      id: 5,
      categoryId: 3,
      authorId: 40,
      title: 'Monty Python: Almost the Truth - Lawyers Cut',
      description:
        'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
      publisher: 'DOBUTAMINE HYDROCHLORIDE',
      publishedDate: 'Cras in purus.',
      pages: 698,
      dimensions: 'fault-tolerant',
      language: 'Malagasy',
      isbn: '060457494-0',
      condition: 'new',
      price: 355396,
      currentStock: 2,
      soldCopies: 46,
      thumbnail:
        'https://robohash.org/voluptatemoptionon.png?size=50x75&set=set1',
      photos: 'tempus vivamus in felis',
      slug: 'hardware',
      active: false,
    },
    {
      id: 6,
      categoryId: 3,
      authorId: 23,
      title: 'Aqua Teen Hunger Force Colon Movie Film for Theaters',
      description:
        'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.',
      publisher: 'Acetaminophen',
      publishedDate: 'Duis ac nibh.',
      pages: 804,
      dimensions: 'website',
      language: 'Bislama',
      isbn: '245489914-0',
      condition: 'used',
      price: 119475,
      currentStock: 16,
      soldCopies: 15,
      thumbnail: 'https://robohash.org/quiseoseligendi.png?size=50x75&set=set1',
      photos: 'at turpis a pede posuere',
      slug: 'cohesive',
      active: true,
    },
    {
      id: 7,
      categoryId: 5,
      authorId: 25,
      title: '7th Cavalry (Seventh Cavalry)',
      description:
        'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
      publisher: 'Alprazolam',
      publishedDate: 'In congue.',
      pages: 825,
      dimensions: 'real-time',
      language: 'Kannada',
      isbn: '705821390-9',
      condition: 'used',
      price: 1313420,
      currentStock: 60,
      soldCopies: 2,
      thumbnail:
        'https://robohash.org/nisifaciliscorporis.png?size=50x75&set=set1',
      photos: 'placerat ante nulla justo',
      slug: 'strategy',
      active: true,
    },
    {
      id: 8,
      categoryId: 3,
      authorId: 14,
      title: 'Saturday Night Fever',
      description:
        'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
      publisher: 'Aspirin',
      publishedDate: 'Quisque ut erat.',
      pages: 743,
      dimensions: 'methodical',
      language: 'Montenegrin',
      isbn: '024805453-8',
      condition: 'used',
      price: 1310941,
      currentStock: 20,
      soldCopies: 21,
      thumbnail: 'https://robohash.org/quasieumaut.png?size=50x75&set=set1',
      photos: 'ut',
      slug: 'monitoring',
      active: true,
    },
    {
      id: 9,
      categoryId: 2,
      authorId: 11,
      title: 'Carancho',
      description:
        'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.',
      publisher: 'hydroxyzine hydrochloride',
      publishedDate: 'Suspendisse ornare consequat lectus.',
      pages: 173,
      dimensions: 'database',
      language: 'Georgian',
      isbn: '198960358-0',
      condition: 'used',
      price: 1318928,
      currentStock: 21,
      soldCopies: 22,
      thumbnail: 'https://robohash.org/quianihilsit.png?size=50x75&set=set1',
      photos: 'primis',
      slug: 'bandwidth-monitored',
      active: true,
    },
    {
      id: 10,
      categoryId: 4,
      authorId: 3,
      title: 'Tuff Turf',
      description:
        'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
      publisher: 'AVOBENZONE, OCTINOXATE',
      publishedDate: 'Proin at turpis a pede posuere nonummy.',
      pages: 594,
      dimensions: 'secondary',
      language: 'Tsonga',
      isbn: '547104535-1',
      condition: 'used',
      price: 1218571,
      currentStock: 41,
      soldCopies: 43,
      thumbnail:
        'https://robohash.org/consecteturquisqui.png?size=50x75&set=set1',
      photos: 'feugiat',
      slug: 'tangible',
      active: true,
    },
    {
      id: 11,
      categoryId: 7,
      authorId: 36,
      title: "Joni's Promise",
      description:
        'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.',
      publisher: 'hydrocortisone',
      publishedDate: 'Donec quis orci eget orci vehicula.',
      pages: 90,
      dimensions: 'Synergistic',
      language: 'French',
      isbn: '088122444-8',
      condition: 'used',
      price: 613496,
      currentStock: 73,
      soldCopies: 15,
      thumbnail: 'https://robohash.org/enimnemodolorem.png?size=50x75&set=set1',
      photos: 'neque',
      slug: 'Automated',
      active: false,
    },
    {
      id: 12,
      categoryId: 3,
      authorId: 48,
      title: 'Partners: The Movie II (Aibô: Gekijô-ban II)',
      description:
        'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',
      publisher: 'Codfish',
      publishedDate: 'Vestibulum rutrum rutrum neque.',
      pages: 893,
      dimensions: 'Exclusive',
      language: 'Macedonian',
      isbn: '676078701-3',
      condition: 'new',
      price: 1010651,
      currentStock: 78,
      soldCopies: 27,
      thumbnail: 'https://robohash.org/sitnemonon.png?size=50x75&set=set1',
      photos: 'pellentesque eget',
      slug: 'approach',
      active: true,
    },
    {
      id: 13,
      categoryId: 2,
      authorId: 5,
      title: 'Face',
      description:
        'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.',
      publisher: 'Fagopyrum, Croton , Aesculus, Sulphur , Kali sulph , Cina',
      publishedDate: 'Mauris enim leo, rhoncus sed.',
      pages: 63,
      dimensions: 'Expanded',
      language: 'Swati',
      isbn: '803981517-7',
      condition: 'new',
      price: 1201307,
      currentStock: 62,
      soldCopies: 48,
      thumbnail:
        'https://robohash.org/repellatestsapiente.png?size=50x75&set=set1',
      photos: 'parturient montes',
      slug: 'multi-tasking',
      active: false,
    },
    {
      id: 14,
      categoryId: 1,
      authorId: 29,
      title: 'Robin and Marian',
      description:
        'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.',
      publisher: 'povidone iodine',
      publishedDate: 'Cum sociis natoque penatibus augue.',
      pages: 536,
      dimensions: 'reciprocal',
      language: 'Malayalam',
      isbn: '215695599-9',
      condition: 'used',
      price: 1072400,
      currentStock: 34,
      soldCopies: 33,
      thumbnail:
        'https://robohash.org/consequunturnobisad.png?size=50x75&set=set1',
      photos: 'et tempus semper est',
      slug: 'Enhanced',
      active: true,
    },
    {
      id: 15,
      categoryId: 7,
      authorId: 46,
      title: 'After Earth',
      description:
        'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.',
      publisher: 'zolpidem tartrate',
      publishedDate: 'Nam congue, risus semper porta lectus.',
      pages: 573,
      dimensions: 'time-frame',
      language: 'Hiri Motu',
      isbn: '246927100-2',
      condition: 'used',
      price: 1222713,
      currentStock: 22,
      soldCopies: 2,
      thumbnail: 'https://robohash.org/odioipsumest.png?size=50x75&set=set1',
      photos: 'ultricies eu nibh quisque',
      slug: 'Optional',
      active: true,
    },
    {
      id: 16,
      categoryId: 7,
      authorId: 39,
      title: 'Doulos, Le',
      description:
        'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',
      publisher: 'armodafinil',
      publishedDate: 'Fusce consequat. Nulla nisl.',
      pages: 717,
      dimensions: 'Re-engineered',
      language: 'Filipino',
      isbn: '990406056-8',
      condition: 'used',
      price: 1391406,
      currentStock: 1,
      soldCopies: 13,
      thumbnail:
        'https://robohash.org/voluptateetnihil.png?size=50x75&set=set1',
      photos: 'pede morbi porttitor lorem id',
      slug: 'knowledge user',
      active: true,
    },
    {
      id: 17,
      categoryId: 7,
      authorId: 46,
      title: 'Ricky',
      description:
        'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.',
      publisher: 'Acetaminophen, Diphenhydramine HCl',
      publishedDate: 'Curabitur gravida nisi at nibh.',
      pages: 378,
      dimensions: 'Re-engineered',
      language: 'Swedish',
      isbn: '427739008-0',
      condition: 'used',
      price: 133114,
      currentStock: 98,
      soldCopies: 33,
      thumbnail:
        'https://robohash.org/quisdignissimosdicta.png?size=50x75&set=set1',
      photos: 'scelerisque mauris sit amet eros',
      slug: 'open architecture',
      active: true,
    },
    {
      id: 18,
      categoryId: 3,
      authorId: 41,
      title: 'V2: Dead Angel (Vares 2 - Jäätynyt Enkeli)',
      description:
        'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
      publisher: 'Glipizide',
      publishedDate: 'Duis bibendum.',
      pages: 561,
      dimensions: 'alliance',
      language: 'Khmer',
      isbn: '747134169-6',
      condition: 'used',
      price: 656036,
      currentStock: 39,
      soldCopies: 20,
      thumbnail: 'https://robohash.org/quisquameosillo.png?size=50x75&set=set1',
      photos: 'aliquam convallis nunc proin',
      slug: 'Team-oriented',
      active: false,
    },
    {
      id: 19,
      categoryId: 5,
      authorId: 29,
      title: 'Naqoyqatsi',
      description:
        'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',
      publisher: 'Apis mellifica, Argentum Nitricum., Arnica montana',
      publishedDate: 'Donec vitae nisi.',
      pages: 273,
      dimensions: 'Virtual',
      language: 'Quechua',
      isbn: '053968109-1',
      condition: 'used',
      price: 158894,
      currentStock: 18,
      soldCopies: 47,
      thumbnail: 'https://robohash.org/aperiammodiab.png?size=50x75&set=set1',
      photos: 'dolor sit amet consectetuer adipiscing',
      slug: 'leading edge',
      active: false,
    },
    {
      id: 20,
      categoryId: 8,
      authorId: 11,
      title: 'Inequality for All',
      description:
        'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.',
      publisher: 'Glimepiride',
      publishedDate: 'Praesent blandit. Nam nulla.',
      pages: 477,
      dimensions: 'info-mediaries',
      language: 'Arabic',
      isbn: '085066189-7',
      condition: 'used',
      price: 805729,
      currentStock: 71,
      soldCopies: 11,
      thumbnail: 'https://robohash.org/veleumqui.png?size=50x75&set=set1',
      photos: 'purus',
      slug: 'Horizontal',
      active: false,
    },
    {
      id: 21,
      categoryId: 9,
      authorId: 33,
      title: 'The Lost Squadron',
      description:
        'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.',
      publisher: 'APIS MELLIFERA, ARNICA MONTANA.',
      publishedDate: 'In hac habitasse platea dictumst.',
      pages: 458,
      dimensions: 'object-oriented',
      language: 'Norwegian',
      isbn: '939170605-3',
      condition: 'new',
      price: 1175727,
      currentStock: 100,
      soldCopies: 36,
      thumbnail: 'https://robohash.org/quisaliasminus.png?size=50x75&set=set1',
      photos: 'non interdum',
      slug: 'encoding',
      active: true,
    },
    {
      id: 22,
      categoryId: 4,
      authorId: 46,
      title: 'Stars in My Crown',
      description:
        'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.',
      publisher: 'cetirizine hydrochloride',
      publishedDate: 'Vestibulum sed magna at nunc commodo placerat.',
      pages: 646,
      dimensions: 'Graphic Interface',
      language: 'Yiddish',
      isbn: '904882313-7',
      condition: 'new',
      price: 319379,
      currentStock: 24,
      soldCopies: 9,
      thumbnail:
        'https://robohash.org/etaspernaturneque.png?size=50x75&set=set1',
      photos: 'nulla mollis',
      slug: 'paradigm',
      active: false,
    },
    {
      id: 23,
      categoryId: 7,
      authorId: 47,
      title: 'Crimes Against Humanity',
      description:
        'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
      publisher: 'Acetaminophen, Chlorpheniramine maleate',
      publishedDate: 'Vestibulum ante ipsum primis in faucibus.',
      pages: 613,
      dimensions: 'Versatile',
      language: 'Gujarati',
      isbn: '596350981-5',
      condition: 'used',
      price: 1382303,
      currentStock: 30,
      soldCopies: 38,
      thumbnail:
        'https://robohash.org/minimaetaspernatur.png?size=50x75&set=set1',
      photos: 'lacinia aenean sit amet justo',
      slug: 'zero defect',
      active: true,
    },
    {
      id: 24,
      categoryId: 4,
      authorId: 50,
      title: 'Sunday Day in Hell, A (En forårsdag i Helvede)',
      description:
        'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.',
      publisher: 'Camphor (Synthetic) and Menthol',
      publishedDate: 'Quisque erat eros, viverra eget.',
      pages: 82,
      dimensions: 'Cloned',
      language: 'Kurdish',
      isbn: '233371221-X',
      condition: 'new',
      price: 224180,
      currentStock: 2,
      soldCopies: 31,
      thumbnail:
        'https://robohash.org/vitaemollitiadistinctio.png?size=50x75&set=set1',
      photos: 'et commodo vulputate justo in',
      slug: 'motivating',
      active: true,
    },
    {
      id: 25,
      categoryId: 5,
      authorId: 26,
      title: 'Sydney White',
      description:
        'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.',
      publisher: 'Pramipexole dihydrochloride',
      publishedDate:
        'In hac habitasse platea dictumst. Etiam faucibus cursus urna.',
      pages: 746,
      dimensions: 'Operative',
      language: 'Sotho',
      isbn: '996006134-5',
      condition: 'new',
      price: 689489,
      currentStock: 9,
      soldCopies: 30,
      thumbnail: 'https://robohash.org/autbeataesed.png?size=50x75&set=set1',
      photos: 'sapien dignissim vestibulum vestibulum ante',
      slug: 'Up-sized',
      active: true,
    },
    {
      id: 26,
      categoryId: 5,
      authorId: 28,
      title: 'Crocodile (Ag-o)',
      description:
        'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.',
      publisher: 'hypromellose',
      publishedDate: 'Integer non velit. Donec diam neque.',
      pages: 488,
      dimensions: '3rd generation',
      language: 'Romanian',
      isbn: '824839501-4',
      condition: 'new',
      price: 1019362,
      currentStock: 1,
      soldCopies: 28,
      thumbnail:
        'https://robohash.org/etfacilisrepudiandae.png?size=50x75&set=set1',
      photos: 'nulla',
      slug: 'Automated',
      active: true,
    },
    {
      id: 27,
      categoryId: 7,
      authorId: 25,
      title: 'Prince Valiant',
      description:
        'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.',
      publisher: 'Acetaminophen',
      publishedDate: 'In hac habitasse platea dictumst.',
      pages: 956,
      dimensions: 'web-enabled',
      language: 'Estonian',
      isbn: '462868118-X',
      condition: 'new',
      price: 395062,
      currentStock: 30,
      soldCopies: 40,
      thumbnail: 'https://robohash.org/tenetureterror.png?size=50x75&set=set1',
      photos: 'donec diam neque',
      slug: 'Streamlined',
      active: false,
    },
    {
      id: 28,
      categoryId: 8,
      authorId: 46,
      title: 'White Shadows in the South Seas',
      description:
        'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.',
      publisher: 'OCTINOXATE and TITANIUM DIOXIDE',
      publishedDate: 'Curabitur gravida nisi at nibh.',
      pages: 866,
      dimensions: 'client-server',
      language: 'Amharic',
      isbn: '779000118-3',
      condition: 'new',
      price: 728100,
      currentStock: 56,
      soldCopies: 17,
      thumbnail: 'https://robohash.org/iurequamalias.png?size=50x75&set=set1',
      photos: 'pellentesque at nulla suspendisse potenti',
      slug: 'Fully-configurable',
      active: true,
    },
    {
      id: 29,
      categoryId: 8,
      authorId: 2,
      title:
        'White Light/Black Rain: The Destruction of Hiroshima and Nagasaki',
      description:
        'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',
      publisher: 'OCTINOXATE, OCTISALATE, AVOBENZONE',
      publishedDate: 'Nullam varius.',
      pages: 83,
      dimensions: 'national',
      language: 'Gagauz',
      isbn: '821553985-8',
      condition: 'new',
      price: 1495165,
      currentStock: 62,
      soldCopies: 30,
      thumbnail: 'https://robohash.org/nihiletrepellat.png?size=50x75&set=set1',
      photos: 'et eros vestibulum',
      slug: 'contextually-based',
      active: false,
    },
    {
      id: 30,
      categoryId: 7,
      authorId: 19,
      title: 'Commando',
      description:
        'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.',
      publisher: 'Salmon',
      publishedDate: 'Morbi a ipsum. Integer a nibh.',
      pages: 722,
      dimensions: 'systemic',
      language: 'Korean',
      isbn: '510133636-X',
      condition: 'new',
      price: 1368437,
      currentStock: 35,
      soldCopies: 49,
      thumbnail:
        'https://robohash.org/dictaettemporibus.png?size=50x75&set=set1',
      photos: 'orci luctus',
      slug: 'core',
      active: true,
    },
    {
      id: 31,
      categoryId: 9,
      authorId: 8,
      title: 'Dog Soldiers',
      description:
        'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',
      publisher: 'ALCOHOL',
      publishedDate: 'Nullam molestie nibh in lectus.',
      pages: 566,
      dimensions: 'asymmetric',
      language: 'Papiamento',
      isbn: '280589308-5',
      condition: 'new',
      price: 1451983,
      currentStock: 83,
      soldCopies: 48,
      thumbnail:
        'https://robohash.org/sintexcepturiofficiis.png?size=50x75&set=set1',
      photos: 'ut suscipit a',
      slug: 'application',
      active: true,
    },
    {
      id: 32,
      categoryId: 4,
      authorId: 30,
      title: 'For Love of Ivy',
      description:
        'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
      publisher: 'Salicylic Acid',
      publishedDate: 'Mauris lacinia sapien quis libero.',
      pages: 353,
      dimensions: 'executive',
      language: 'Filipino',
      isbn: '713894613-9',
      condition: 'new',
      price: 1286909,
      currentStock: 96,
      soldCopies: 26,
      thumbnail:
        'https://robohash.org/essereprehenderitodit.png?size=50x75&set=set1',
      photos: 'auctor sed tristique in',
      slug: 'bifurcated',
      active: false,
    },
    {
      id: 33,
      categoryId: 10,
      authorId: 26,
      title: 'Flower of Evil, The (Fleur du mal, La)',
      description:
        'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.',
      publisher: 'Cetirizine Hydrochloride',
      publishedDate: 'Nulla facilisi.',
      pages: 292,
      dimensions: 'Cross-platform',
      language: 'Hungarian',
      isbn: '386464218-3',
      condition: 'new',
      price: 430845,
      currentStock: 27,
      soldCopies: 42,
      thumbnail: 'https://robohash.org/odioaccusamusin.png?size=50x75&set=set1',
      photos: 'enim blandit',
      slug: 'Focused',
      active: false,
    },
    {
      id: 34,
      categoryId: 3,
      authorId: 27,
      title: 'My Name Is Julia Ross',
      description:
        'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.',
      publisher: 'Fagopyrum, Croton',
      publishedDate: 'Mauris sit amet eros.',
      pages: 468,
      dimensions: 'Grass-roots',
      language: 'Punjabi',
      isbn: '014702144-8',
      condition: 'new',
      price: 570174,
      currentStock: 70,
      soldCopies: 9,
      thumbnail:
        'https://robohash.org/voluptatemdoloresunde.png?size=50x75&set=set1',
      photos: 'id',
      slug: 'upward-trending',
      active: false,
    },
    {
      id: 35,
      categoryId: 1,
      authorId: 2,
      title: 'Salvation, The',
      description:
        'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.',
      publisher: 'Lithium Carbonate',
      publishedDate: 'Nam dui.',
      pages: 598,
      dimensions: 'Pre-emptive',
      language: 'Thai',
      isbn: '407684685-0',
      condition: 'used',
      price: 888988,
      currentStock: 0,
      soldCopies: 15,
      thumbnail:
        'https://robohash.org/etetperspiciatis.png?size=50x75&set=set1',
      photos: 'nulla sed vel enim sit',
      slug: 'global',
      active: true,
    },
    {
      id: 36,
      categoryId: 5,
      authorId: 16,
      title: 'Farewell, The (Abschied - Brechts letzter Sommer)',
      description:
        'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.',
      publisher: 'IBUPROFEN',
      publishedDate: 'Nam dui.',
      pages: 240,
      dimensions: 'well-modulated',
      language: 'Czech',
      isbn: '785923810-1',
      condition: 'used',
      price: 1346364,
      currentStock: 66,
      soldCopies: 7,
      thumbnail: 'https://robohash.org/deseruntquosit.png?size=50x75&set=set1',
      photos: 'proin risus praesent lectus',
      slug: 'Extended',
      active: false,
    },
    {
      id: 37,
      categoryId: 5,
      authorId: 45,
      title: 'Fate (Yazgi)',
      description:
        'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
      publisher: 'Promethazine Hydrochloride',
      publishedDate: 'Nulla ac enim. In tempor, turpis nec euismod.',
      pages: 566,
      dimensions: 'Inverse',
      language: 'Oriya',
      isbn: '496359356-4',
      condition: 'used',
      price: 585652,
      currentStock: 78,
      soldCopies: 36,
      thumbnail:
        'https://robohash.org/nonasperioressequi.png?size=50x75&set=set1',
      photos: 'duis mattis egestas',
      slug: 'Re-contextualized',
      active: true,
    },
    {
      id: 38,
      categoryId: 3,
      authorId: 31,
      title: 'Hukkle',
      description:
        'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.',
      publisher: 'Menthol',
      publishedDate: 'Integer ac neque. Duis bibendum.',
      pages: 148,
      dimensions: 'dynamic',
      language: 'Malay',
      isbn: '917604413-0',
      condition: 'used',
      price: 535074,
      currentStock: 46,
      soldCopies: 41,
      thumbnail:
        'https://robohash.org/dignissimosdolorumrepellendus.png?size=50x75&set=set1',
      photos: 'condimentum id luctus nec molestie',
      slug: 'Customer-focused',
      active: true,
    },
    {
      id: 39,
      categoryId: 2,
      authorId: 12,
      title: 'Love Potion #9',
      description:
        'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.',
      publisher: 'Levothyroxine Sodium',
      publishedDate: 'Vestibulum ante ipsum primis.',
      pages: 907,
      dimensions: 'solution-oriented',
      language: 'Tajik',
      isbn: '583484806-0',
      condition: 'used',
      price: 261293,
      currentStock: 5,
      soldCopies: 42,
      thumbnail: 'https://robohash.org/etquamaliquid.png?size=50x75&set=set1',
      photos: 'rutrum neque aenean auctor',
      slug: 'Triple-buffered',
      active: false,
    },
    {
      id: 40,
      categoryId: 1,
      authorId: 7,
      title: 'Confessor, The (a.k.a. The Good Shepherd)',
      description:
        'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
      publisher: 'OXYGEN',
      publishedDate: 'Curabitur in libero ut massa.',
      pages: 995,
      dimensions: 'Diverse',
      language: 'Irish Gaelic',
      isbn: '336805618-2',
      condition: 'used',
      price: 1133143,
      currentStock: 97,
      soldCopies: 49,
      thumbnail: 'https://robohash.org/suscipitatet.png?size=50x75&set=set1',
      photos: 'vestibulum aliquet ultrices',
      slug: 'incremental',
      active: false,
    },
    {
      id: 41,
      categoryId: 6,
      authorId: 23,
      title: 'Chasing Mavericks',
      description:
        'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.',
      publisher: 'norgestrel/ethinyl estradiol',
      publishedDate: 'Donec posuere metus vitae ipsum.',
      pages: 442,
      dimensions: 'stable',
      language: 'Dari',
      isbn: '626405972-2',
      condition: 'used',
      price: 551029,
      currentStock: 0,
      soldCopies: 44,
      thumbnail:
        'https://robohash.org/porroautsapiente.png?size=50x75&set=set1',
      photos: 'est et tempus',
      slug: 'Operative',
      active: false,
    },
    {
      id: 42,
      categoryId: 3,
      authorId: 19,
      title: 'Lady Killer',
      description:
        'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.',
      publisher: 'psyllium husk',
      publishedDate: 'Integer aliquet, massa id lobortis convallis.',
      pages: 387,
      dimensions: 'circuit',
      language: 'Portuguese',
      isbn: '882639070-3',
      condition: 'used',
      price: 1013316,
      currentStock: 39,
      soldCopies: 13,
      thumbnail: 'https://robohash.org/aspernaturautet.png?size=50x75&set=set1',
      photos: 'luctus tincidunt',
      slug: 'demand-driven',
      active: false,
    },
    {
      id: 43,
      categoryId: 10,
      authorId: 19,
      title: 'Valentino',
      description:
        'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.',
      publisher: 'GUAIFENESIN',
      publishedDate: 'Nullam orci pede, venenatis non, felis.',
      pages: 337,
      dimensions: 'Devolved',
      language: 'Albanian',
      isbn: '419875593-0',
      condition: 'used',
      price: 1042893,
      currentStock: 44,
      soldCopies: 29,
      thumbnail:
        'https://robohash.org/voluptasillumdolor.png?size=50x75&set=set1',
      photos: 'ipsum primis in faucibus orci',
      slug: 'systemic',
      active: true,
    },
    {
      id: 44,
      categoryId: 2,
      authorId: 13,
      title: 'Murder in the First',
      description:
        'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',
      publisher: 'Aralia racemosa, Arsenicum album',
      publishedDate: 'In hac habitasse platea dictumst.',
      pages: 707,
      dimensions: 'Innovative',
      language: 'Dutch',
      isbn: '699333909-9',
      condition: 'used',
      price: 934731,
      currentStock: 88,
      soldCopies: 46,
      thumbnail:
        'https://robohash.org/seddebitisreprehenderit.png?size=50x75&set=set1',
      photos: 'leo maecenas pulvinar lobortis est',
      slug: 'capacity',
      active: false,
    },
    {
      id: 45,
      categoryId: 4,
      authorId: 29,
      title: 'Little Criminals',
      description:
        'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc vel sem. Sed sagittis. Nam congue, porta volutpat, libero quis orci.',
      publisher: 'BENZTROPINE MESYLATE',
      publishedDate: 'Nullam molestie nibh in lectus. Pellentesque at nulla.',
      pages: 332,
      dimensions: 'radical',
      language: 'Indonesian',
      isbn: '894378334-5',
      condition: 'used',
      price: 254812,
      currentStock: 93,
      soldCopies: 45,
      thumbnail: 'https://robohash.org/uterroripsam.png?size=50x75&set=set1',
      photos: 'dolor sit amet consectetuer',
      slug: 'attitude-oriented',
      active: false,
    },
    {
      id: 46,
      categoryId: 9,
      authorId: 38,
      title: 'Cheeky (Trasgredire)',
      description:
        'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.',
      publisher: 'Bismuth subsalicylate',
      publishedDate:
        'Nam congue, risus semper porta volutpat, quam pede lobortis ligula.',
      pages: 519,
      dimensions: 'logistical',
      language: 'Finnish',
      isbn: '541166409-8',
      condition: 'used',
      price: 697891,
      currentStock: 12,
      soldCopies: 2,
      thumbnail:
        'https://robohash.org/doloremfacilisimpedit.png?size=50x75&set=set1',
      photos: 'nulla nunc purus',
      slug: 'Self-enabling',
      active: true,
    },
    {
      id: 47,
      categoryId: 8,
      authorId: 37,
      title: 'Osaka Elegy (Naniwa erejî)',
      description:
        'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.',
      publisher: 'Glimepiride',
      publishedDate: 'Donec ut mauris eget massa tempor convallis.',
      pages: 182,
      dimensions: 'analyzer',
      language: 'West Frisian',
      isbn: '089195714-6',
      condition: 'used',
      price: 707908,
      currentStock: 8,
      soldCopies: 49,
      thumbnail:
        'https://robohash.org/reiciendissolutamolestias.png?size=50x75&set=set1',
      photos: 'vulputate nonummy maecenas tincidunt lacus',
      slug: 'user-facing',
      active: true,
    },
    {
      id: 48,
      categoryId: 9,
      authorId: 14,
      title: 'Gregory Go Boom',
      description:
        'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.',
      publisher: 'TRICLOSAN',
      publishedDate: 'Nunc nisl. Duis bibendum, felis sed interdum venenatis.',
      pages: 155,
      dimensions: 'capacity',
      language: 'Georgian',
      isbn: '817258516-0',
      condition: 'used',
      price: 181925,
      currentStock: 52,
      soldCopies: 10,
      thumbnail:
        'https://robohash.org/quisquamdeserunteos.png?size=50x75&set=set1',
      photos: 'ligula vehicula',
      slug: 'zero administration',
      active: true,
    },
    {
      id: 49,
      categoryId: 9,
      authorId: 22,
      title:
        "Dexter the Dragon & Bumble the Bear (a.k.a. Dragon That Wasn't (Or Was He?), The) (Als je begrijpt wat ik bedoel)",
      description:
        'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.',
      publisher: 'Cimetidine',
      publishedDate: 'Curabitur gravida nisi at nibh.',
      pages: 61,
      dimensions: 'installation',
      language: 'Arabic',
      isbn: '997308110-2',
      condition: 'used',
      price: 1363084,
      currentStock: 68,
      soldCopies: 47,
      thumbnail: 'https://robohash.org/blanditiiseteos.png?size=50x75&set=set1',
      photos: 'ut',
      slug: 'clear-thinking',
      active: true,
    },
    {
      id: 50,
      categoryId: 5,
      authorId: 21,
      title: 'Madness of King George, The',
      description:
        'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.',
      publisher: 'Ibuprofen',
      publishedDate: 'In tempor, turpis nec euismod scelerisque.',
      pages: 610,
      dimensions: 'Customer-focused',
      language: 'Georgian',
      isbn: '382644341-1',
      condition: 'used',
      price: 1409275,
      currentStock: 55,
      soldCopies: 23,
      thumbnail:
        'https://robohash.org/voluptateearumnon.png?size=50x75&set=set1',
      photos: 'sapien sapien non',
      slug: 'adapter',
      active: false,
    },
  ]);

  // orders_books
  await knex('orders_books').insert([
    {
      orderId: 1,
      bookId: 1,
    },
  ]);

  // books_authors
  await knex('books_authors').insert([
    {
      bookId: 1,
      authorId: 1,
    },
  ]);
}
